# Generated by Django 5.0.6 on 2024-07-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0002_alter_filechunk_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filechunk',
            name='iv',
        ),
    ]
